Check for functions instead of hardcoding their availability

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,22 +1,75 @@
 #!/bin/sh
 
+# function name, header name, replacement to source. Stdin is test program
+have_function() {
+	cat < /dev/null > test.c
+	for header in $2; do
+		echo "#include <$header>" >> test.c
+	done
+	echo "int main(void) {" >> test.c
+	cat - >> test.c
+	echo "}" >> test.c
+
+	printf -- "Checking for function $1... "
+	cc test.c 2>/dev/null
+	ex=$?
+	if [ $ex -eq 0 ]; then
+		./a.out
+		ex=$?
+		rm a.out
+	fi
+	if [ $ex -ne 0 ]; then
+		if [ "$3" = "NULL" ]; then
+			echo "#define $4 $5" >> config.h
+		else
+			echo SRCS += $3 >> config.mk
+		fi
+		printf 'Not Found\n'
+	else
+		printf 'Found\n'
+	fi
+	rm test.c
+}
+
+# optional, flag name
+have_compiler_flag() {
+	optional=$1
+	shift 1
+	printf -- "Checking for ${optional} compiler flag"
+	if [ $# -ne 1 ]; then
+		printf 's'
+	fi
+	printf ' '
+	for flag in $@; do
+		printf -- "${flag} "
+	done
+	printf '... '
+	cat <<- EOF > test.c
+		int main(void) {  }
+		EOF
+	cc $@ test.c
+	if [ $? -eq 0 ]; then
+		echo CFLAGS += $@ >> config.mk
+		printf 'Found\n'
+	else
+		printf 'Not Found\n'
+		if [ "${optional}" = "required" ]; then
+			exit 1
+		fi
+	fi
+	rm test.c
+}
+
 system="$(uname -s)"
 
 if [ "${system}" = "FreeBSD" ]; then
+	CC=cc
 	PREFIX=/usr/local/
-	HAVE_STRTONUM=1
 elif [ "${system}" = "NetBSD" ]; then
 	PREFIX=/usr/pkg/
-	HAVE_MDMP=1
-	HAVE_STRTONUM=1
 elif [ "${system}" = "OpenBSD" ]; then
 	PREFIX=/usr/local/
-	HAVE_MDMP=1
-	HAVE_STRTONUM=1
-	HAVE_PLEDGE=1
-	HAVE_UNVEIL=1
 elif [ "${system}" = "Linux" ]; then
-	HAVE_MDMP=1
 	PREFIX=/usr/local/
 fi
 
@@ -24,19 +77,70 @@ cat < /dev/null > config.mk
 cat < /dev/null > config.h
 echo "#ifndef MAILZ_CONFIG_H" >> config.h
 echo "#define MAILZ_CONFIG_H" >> config.h
-if [ -n "${HAVE_MDMP}" ]; then
-	echo CFLAGS += -MD -MP >> config.mk
-fi
-if [ -z "${HAVE_STRTONUM}" ]; then
-	echo SRCS += strtonum.c >> config.mk
-fi
-if [ -z "${HAVE_PLEDGE}" ]; then
-	echo "#define pledge(a, b) 0" >> config.h
-fi
-if [ -z "${HAVE_UNVEIL}" ]; then
-	echo "#define unveil(a, b) 0" >> config.h
-fi
+
+have_function unveil "fcntl.h unistd.h" NULL "unveil(a, b)" 0 <<-EOF
+	char buf[] = "/tmp/unveiltest.XXXXXXXXXX";
+	int rv = 1;
+	if (mkstemp(buf) == -1)
+		return 1;
+	if (unveil(buf, "cr") == -1)
+		goto unlink;
+	if (unveil(NULL, NULL) == -1)
+		goto unlink;
+	if (open(buf, O_RDONLY) == -1)
+		goto unlink;
+	rv = 0;
+	unlink:
+	if (unlink(buf) == -1)
+		return 1;
+	return rv;
+	EOF
+
+have_function pledge unistd.h NULL "pledge(a, b)" 0 <<-EOF
+	char buf[1];
+	if (pledge("stdio", NULL) == -1)
+		return 1;
+	read(STDIN_FILENO, buf, 1);
+	return 0;
+	EOF
+
+have_function strtonum stdlib.h strtonum.c <<-EOF
+	int val;
+	const char *errstr;
+
+	val = strtonum("1231", 0, 1231, &errstr);
+	if (errstr != NULL || val != 1231)
+		return 1;
+	strtonum("98328432998432", 0, 1, &errstr);
+	if (errstr == NULL)
+		return 1;
+	strtonum("Hello!", 0, 7, &errstr);
+	if (errstr == NULL)
+		return 1;
+	return 0;
+	EOF
+
+have_function reallocarray stdlib.h reallocarray.c <<-EOF
+	int *vals;
+
+	if ((vals = reallocarray(NULL, 1, sizeof(*vals))) == NULL)
+		return 1;
+	vals[0] = 46;
+	if ((vals = reallocarray(vals, 2, sizeof(*vals))) == NULL)
+		return 1;
+	if (vals[0] != 46)
+		return 1;
+	return 0;
+	EOF
+
 echo "#define PREFIX \"${PREFIX}\"" >> config.h
-echo "PREFIX = ${PREFIX}" >> config.mk
 echo "#endif /* MAILZ_CONFIG_H */" >> config.h
-echo CFLAGS += -include config.h >> config.mk
+
+have_compiler_flag optional -MD -MP
+have_compiler_flag optional -pipe
+have_compiler_flag required -include config.h
+
+echo "PREFIX = ${PREFIX}" >> config.mk
+if [ -n "${CC}" ]; then
+	echo "CC = ${CC}" >> config.mk
+fi
